jenkinsci/cucumber-reports-plugin

pom.xml
src/main/java/net/masterthought/jenkins/CucumberReportPublisher.java
src/main/resources/net/masterthought/jenkins/CucumberReportPublisher/config.jelly

https://github.com/damianszczepanik/cucumber-reporting/pull/292

Updated plugin after dismissing support for Flash plugin

---

src/main/resources/net/masterthought/jenkins/CucumberReportPublisher/config.jelly

Updated config to match actual fail on.

---

.gitignore
pom.xml
src/main/java/net/masterthought/jenkins/CucumberReportBaseAction.java
src/main/java/net/masterthought/jenkins/CucumberReportProjectAction.java
src/main/java/net/masterthought/jenkins/CucumberReportPublisher.java

Issue jenkinsci/cucumber-reports-plugin/issues/62

Added support for Folder plugin

---

src/main/java/net/masterthought/jenkins/CucumberReportPublisher.java

Report is not generated when there is none JSON file

---

pom.xml
src/main/java/net/masterthought/jenkins/CucumberReportPublisher.java
src/main/resources/net/masterthought/jenkins/CucumberReportPublisher/help.html

Project display name should be displayed in report

---

src/main/java/net/masterthought/jenkins/CucumberReportPublisher.java

JSON files are copied to local cache

---

src/main/java/net/masterthought/jenkins/CucumberReportPublisher.java
src/main/resources/net/masterthought/jenkins/CucumberReportPublisher/Classification/config.jelly
src/main/resources/net/masterthought/jenkins/CucumberReportPublisher/Classification/config.properties
src/main/resources/net/masterthought/jenkins/CucumberReportPublisher/config.jelly
src/main/resources/net/masterthought/jenkins/CucumberReportPublisher/config.properties

Added support for classifications

---

src/main/java/net/masterthought/jenkins/SafeArchiveServingAction.java

The embeddings/ folder of cucumber-html-reports contains content that is created by the build process and should not be served withouth the proper precautions. To ensure this the CSP will be enabled for all files in cucumber-hml-reports unless their direct parent directory is white listed. The current white listed directories are:
- /
- /css
- /fonts
- /images
- /js

Serve untrusted content with CSP enabled.

---

src/main/java/net/masterthought/jenkins/SafeArchiveServingAction.java
src/main/resources/net/masterthought/jenkins/CucumberReportPublisher/config.properties

Report was displayed properly for new executions but failed for old one

Fixed pull #128

---

src/main/java/net/masterthought/jenkins/CucumberReportPublisher.java

Parallel test option stays checked

---

src/main/java/net/masterthought/jenkins/CucumberReportPublisher.java

Support for Jenkins Variables/Parameters in Report Path

---

src/main/java/net/masterthought/jenkins/CucumberReportDescriptor.java
src/main/java/net/masterthought/jenkins/CucumberReportPublisher.java
src/main/java/net/masterthought/jenkins/SafeArchiveServingRunAction.java
src/main/resources/net/masterthought/jenkins/CucumberReportPublisher/config.jelly
src/main/resources/net/masterthought/jenkins/CucumberReportPublisher/config.properties
src/main/resources/net/masterthought/jenkins/Messages.properties

Added support for default ordering

---

src/main/java/net/masterthought/jenkins/CucumberReportPublisher.java

Use SortingMethod.NATURAL as default if it is not set

---

src/main/java/net/masterthought/jenkins/CucumberReportPublisher.java

Fixes natural sorting (2nd patch)

---

src/main/java/net/masterthought/jenkins/CucumberReportPublisher.java

NPE when upgrading from broken version

---

pom.xml
src/main/java/net/masterthought/jenkins/CucumberReportPublisher.java
src/main/resources/plugin.properties

https://github.com/damianszczepanik/cucumber-reporting/issues/571

Version Information Included In HTML Report

---

pom.xml
src/main/java/net/masterthought/jenkins/CucumberReportDescriptor.java
src/main/java/net/masterthought/jenkins/CucumberReportPublisher.java
src/main/resources/index.jelly
src/main/resources/net/masterthought/jenkins/CucumberReportPublisher/config.jelly
src/main/resources/net/masterthought/jenkins/CucumberReportPublisher/config.properties
src/main/resources/net/masterthought/jenkins/CucumberReportPublisher/help-parallelTesting.html
src/main/resources/net/masterthought/jenkins/CucumberReportPublisher/help-reducingMethod.html
src/main/resources/net/masterthought/jenkins/Messages.properties

Read and combine all identically named features into one json report

---

src/main/java/net/masterthought/jenkins/CucumberReportPublisher.java

Fixes backward compatibility

---

src/main/java/net/masterthought/jenkins/CucumberReportPublisher.java
src/main/resources/net/masterthought/jenkins/CucumberReportPublisher/config.jelly
src/main/resources/net/masterthought/jenkins/CucumberReportPublisher/config.properties

Issue damianszczepanik/cucumber-reporting/issues/780

Skips empty JSON reports

---

src/main/java/net/masterthought/jenkins/CucumberReportPublisher.java

Removes cache once the build is completed

---

src/main/java/net/masterthought/jenkins/CucumberReportDescriptor.java
src/main/java/net/masterthought/jenkins/CucumberReportPublisher.java
src/main/resources/index.jelly
src/main/resources/net/masterthought/jenkins/CucumberReportPublisher/config.jelly
src/main/resources/net/masterthought/jenkins/CucumberReportPublisher/config.properties
src/main/resources/net/masterthought/jenkins/CucumberReportPublisher/help-failedFeaturesPercentage.html
src/main/resources/net/masterthought/jenkins/CucumberReportPublisher/help-failedScenariosPercentage.html
src/main/resources/net/masterthought/jenkins/CucumberReportPublisher/help-failedStepsPercentage.html
src/main/resources/net/masterthought/jenkins/CucumberReportPublisher/help-pendingStepsPercentage.html
src/main/resources/net/masterthought/jenkins/CucumberReportPublisher/help-skippedStepsPercentage.html
src/main/resources/net/masterthought/jenkins/CucumberReportPublisher/help-undefinedStepsPercentage.html
src/main/resources/net/masterthought/jenkins/Messages.properties

Add support for thresholds in percentage

---

src/main/java/net/masterthought/jenkins/CucumberReportPublisher.java

Use "File Include Pattern" for selection of files to copy to cache.
Fix #308

fileIncludePattern for copy into cache

---

pom.xml
src/main/java/net/masterthought/jenkins/CucumberReportPublisher.java
src/main/resources/net/masterthought/jenkins/CucumberReportPublisher/config.jelly
src/main/resources/net/masterthought/jenkins/CucumberReportPublisher/config.properties
src/main/resources/net/masterthought/jenkins/CucumberReportPublisher/help-mergeFeaturesWithRetest.html

Enabled mergeFeaturesWithRetest option.
Updated version of parent pom.

Added mergeFeaturesWithRetest option of cucumber-reporting plugin

---

src/main/java/net/masterthought/jenkins/CucumberReportPublisher.java

Each Jenkins build adds a new row 'Report title' inside HTML Classifications table

---

pom.xml
src/main/java/net/masterthought/jenkins/CucumberReportPublisher.java
src/main/resources/net/masterthought/jenkins/CucumberReportPublisher/config.jelly
src/main/resources/net/masterthought/jenkins/CucumberReportPublisher/config.properties
src/main/resources/net/masterthought/jenkins/CucumberReportPublisher/help-customCssFiles.html
src/main/resources/net/masterthought/jenkins/CucumberReportPublisher/help-customJsFiles.html

This adds the cucumber-reporting feature to add custom CSS or JS files to the report.
See https://github.com/damianszczepanik/cucumber-reporting/pull/1015

Add possibility to include custom JS and CSS from WORKSPACE in report

---

pom.xml

Bump up cucumber-reporting libraries

---

pom.xml
src/main/java/net/masterthought/jenkins/CucumberReportDescriptor.java

Hi,
I ran the [Modernize Plugin for Java 8](https://app.moderne.io/recipes/org.openrewrite.jenkins.ModernizePluginForJava8?) recipe to bring up tooling and dependencies to more recent versions. The tooling updates meant SpotBugs caught an existing error that I corrected in a subsequent commit. 
Happy to submit another PR to modernize to [current recommendations](https://www.jenkins.io/doc/developer/plugin-development/choosing-jenkins-baseline/) after this.
Existing tests pass.
```[tasklist]
```

Modernize with latest Java 8 compatible versions

---

pom.xml

Bump up dependencies

---

pom.xml

This reverts commit 8ba5279a0a87589608b71cd51356c23f8959a799.

Revert "[dependency] Bump io.jenkins.tools.bom:bom-2.440.x (#488)"

---

pom.xml

Upgrade to parent org.jenkins-ci.plugins:plugin:5.4

---

pom.xml

Use https://github.com/jenkinsci/commons-collections4-api-plugin and depend on the version provided via `bom`.
None. Rely on `ci.jenkins.io` to test it.

Use commons-collections4-api from bom
